import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Icon } from '@iconify/react';
import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuItem,
  NavigationMenuTrigger,
} from '@/components/ui/navigation-menu';
import { NavigationMenuList } from '@radix-ui/react-navigation-menu';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased border-l border-r max-w-screen-lg mx-auto`}
      >
        <header className='sticky flex flex-row justify-between z-50 py-4 px-8 border-b'>
          <div className='flex flex-row space-x-4 items-center'>
            <p className='text-2xl font-bold'>OTDJ</p>
            <NavigationMenu>
              <NavigationMenuList>
                <NavigationMenuItem>
                  <NavigationMenuTrigger>maimai DX</NavigationMenuTrigger>
                  <NavigationMenuContent>
                    <div className='flex flex-col w-72'>
                      <div className='flex flex-row p-4 space-x-2'>
                        <div className='w-12 h-12 bg-gray-100 rounded-md'></div>
                        <div>
                          <p className='text-base font-bold'>maimai DX</p>
                          <p className='text-sm'>PRiSM (Int&apos;l ver.)</p>
                        </div>
                      </div>
                      <div className='flex flex-row p-4 space-x-2'>
                        <div className='w-12 h-12 bg-gray-100 rounded-md'></div>
                        <div>
                          <p className='text-base font-bold'>SOUND VOLTEX</p>
                          <p className='text-sm'>EXCEED GEAR</p>
                        </div>
                      </div>
                      <div className='flex flex-row p-4 space-x-2'>
                        <div className='w-12 h-12 bg-gray-100 rounded-md'></div>
                        <div>
                          <p className='text-base font-bold'>CHUNITHM</p>
                          <p className='text-sm'>LUMINOUS PLUS (Int&apos;l ver.)</p>
                        </div>
                      </div>
                      <div className='flex flex-row p-4 space-x-2'>
                        <div className='w-12 h-12 bg-gray-100 rounded-md'></div>
                        <div>
                          <p className='text-base font-bold'>beatmania IIDX</p>
                          <p className='text-sm'>32 Pinky Crush</p>
                        </div>
                      </div>
                      <div className='flex flex-row p-4 space-x-2'>
                        <div className='w-12 h-12 bg-gray-100 rounded-md'></div>
                        <div>
                          <p className='text-base font-bold'>pop&apos;n music</p>
                          <p className='text-sm'>Jam&Fizz</p>
                        </div>
                      </div>
                    </div>
                  </NavigationMenuContent>
                </NavigationMenuItem>
              </NavigationMenuList>
            </NavigationMenu>
            <p className='text-sm'>챌린지</p>
            <p className='text-sm'>챌린지팩</p>
          </div>
          <div className='flex flex-row space-x-4 items-center'>
            <Icon icon='solar:settings-linear' width={24} height={24} />
            <Icon icon='solar:user-circle-linear' width={24} height={24} />
            <Icon icon='solar:logout-linear' width={24} height={24} />
          </div>
        </header>
        <main className='container-wrapper'>{children}</main>
      </body>
    </html>
  );
}
